AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-kinesis-consumer

  Sample SAM Template for lambda-kinesis-consumer
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaKinesisConsumer:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-kinesis-consumer/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        PokemonEvent:
          Type: Kinesis
          Properties:
            Stream: !GetAtt PokemonStream.Arn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  PokemonStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 2
  LambdaKinesisLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaKinesisConsumer}"
      RetentionInDays: 1
Outputs:
  LambdaKinesisName:
    Description: "Function name"
    Value: !Ref LambdaKinesisConsumer
  PokemonStreamARN:
    Description: "StreamARN"
    Value: !GetAtt PokemonStream.Arn
